# fly.toml app configuration file generated for quiz-admin-floral-hill-6796 on 2025-03-02T12:38:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rakibdevs'
primary_region = 'mad'

[build]
  # Specify the builder to use. You can use a Dockerfile or a buildpack.
  builder = "heroku/buildpacks:20"  # Example for a Node.js app; change as needed.

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
